---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.2.0
- name: zookeeper
  url: git+https://github.com/cppforlife/zookeeper-release
  version: 0.0.7
- name: kafka
  sha1: 9f8fe52a7098124d0396aeeb946a69283652c734
  url: https://github.com/cloudfoundry-community/kafka-boshrelease/releases/download/v1.2.1/kafka-1.2.1.tgz
  version: 1.2.1
