---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: status
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
- name: kafka-manager
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))
- name: sanity-test
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity-test
    release: kafka

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3586.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

releases:
- name: bpm
  sha1: 6e56cb7a2cb4b844d3c1d8fddcc08335d1f1f5e1
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-0.6.0-ubuntu-trusty-3586.7-20180515-225859-636152916-20180515225908.tgz
  version: 0.6.0
- name: zookeeper
  sha1: d5a67438141ddba22acbfbb3f1bc9c759ed7ae62
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-trusty-3586.7-20180515-225907-338782705-20180515225917.tgz
  version: 0.0.9
- name: kafka
  sha1: 820f891b3d39b256355458c230b7da6093b30f1f
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/kafka/kafka-1.2.1-ubuntu-trusty-3586.7-20180515-225651-383030107-20180515225700.tgz
  version: 1.2.1
